sudo: required
addons:
  chrome: stable

language: node

cache:
  yarn: true
  directories:
    - tests/elm-stuff
    - tests/node_modules

matrix:
    include:
        - os: linux
          env: |
            ELM_VERSION=0.19.0
            TARGET_NODE_VERSION=node
            ELM_BINARY=https://github.com/elm/compiler/releases/download/0.19.0/binaries-for-linux.tar.gz
            CHROMEDRIVER_PLATFORM=linux64
        - os: osx
          env: |
            ELM_VERSION=0.19.0
            TARGET_NODE_VERSION=node
            ELM_BINARY=https://github.com/elm/compiler/releases/download/0.19.0/binaries-for-mac.tar.gz
            CHROMEDRIVER_PLATFORM=mac64



before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - curl -L $ELM_BINARY | tar xz

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - yarn --version
  - ./elm --version
  - export PATH=$PATH:$PWD
  - cd tests
  - yarn
  - cd ..
  # - npm install -g elm@$ELM_VERSION
  # - npm install -g elm-test@beta

before_script:
  - VERSION=$(curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - curl -L -o chromedriver.zip  http://chromedriver.storage.googleapis.com/$VERSION/chromedriver_$CHROMEDRIVER_PLATFORM.zip
  - unzip chromedriver.zip

script:
  # - elm-format --validate src/
  - ./chromedriver &
  - last_pid=$!
  - cd tests
  - yarn --cwd tests test
  - kill -KILL $last_pid
  # - yarn elm-analyse