sudo: required
addons:
  chrome: stable

services:
  - docker

language: node

cache:
  directories:
    - tests/elm-stuff
    - tests/node_modules
    - tests/stats.json

matrix:
    include:
        ### CHROME DRIVER ###
        - os: linux
          env: |
            ELM_VERSION=latest
            TARGET_NODE_VERSION=node
            DRIVER_NAME="Chrome Linux"

        - os: osx
          env: |
            ELM_VERSION=latest
            TARGET_NODE_VERSION=node
            DRIVER_NAME="Chrome OSX"



before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn --cwd tests

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - yarn global add elm@$ELM_VERSION
  - node --version
  - npm --version
  - yarn --version
  - elm --version
  - export PATH=$PATH:$PWD


before_script: |
  curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start --vnc --tmpfs 128

script:
  # - elm-format --validate src/
  - cd tests
  - elm make ./src/Main.elm --optimize --output=bundle.js
  - node ./ci.js
